version: "3.7"
services: 
  app:
    build : 
       context: "./frontend"
       target: "base"
    container_name: "conoha-front"
    image: "okakyo/conoha-front"
    tty: false
    ports:
      - 3000:3000
    depends_on:
      - api
      - redis
    command: "npm run dev"
    volumes:
      - ./frontend/src:/apps/base/src
    environment:
      NODE_ENV: development

  api:
    restart: always
    build : 
      context: "./server"
      target: "base"
    container_name: "conoha-app"
    image: "okakyo/conoha-app"
    command: "npm run dev"
    tty: false
    ports:
      - 3001:3000
    volumes: 
      - ./server/src:/apps/base/src
      - ./server/prisma:/apps/base/prisma
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_URL: 'mysql://${MYSQL_USERNAME}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}'
      REDIS_PORT: ${REDIS_PORT}
      NODE_ENV: development
    depends_on:
      - db
      
  db:
    restart: always
    image: "mariadb:latest"
    container_name: conoha-maindb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  redis:
    restart: always
    image: redis:latest
    container_name: "conoha-redis"
    volumes:
      - ./docker/redis/data:/data
    ports:
      - 63790:6379
    command: redis-server --appendonly yes
