# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SK}}
          name: id_rsa 
          known_hosts: ${{secrets.KNOWN_HOSTS}}
      - name: Set Docker context
        run: |
          docker context create --default-stack-orchestrator=swarm --docker "host=ssh://${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:${{secrets.SSH_PORT}}" remote
      - name: Deploy
        run: |
          docker-compose --context remote stop
          docker-compose --context remote up --build -d 
